# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/edwardair/Specs.git'

target :'Sqlit' do
  pod 'WGFMDB', :path => '../WGFMDB.podspec'
#    pod 'FMDB', '~> 2.5'
#    pod 'WGKit', :git => 'https://github.com/edwardair/WGCategory.git', :tag => '0.4.0'
    #pod 'WGFMDB', :git => 'https://github.com/edwardair/WGFMDB.git', :tag => '0.2'
end

